//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Tabulador = new HashSet<Tabulador>();
        }

        public int idEmpleado { get; set; }

        [DisplayName("Código")]
        [Required(ErrorMessage = "Por favor ingrese el código de empleado. Ejemplo: EMP000")]
        public string codigo { get; set; }

        [DisplayName("Nombre")]
        [Required(ErrorMessage = "Por favor ingrese el nombre del empleado.")]
        public string nombre { get; set; }

        [DisplayName("Apellidos")]
        [Required(ErrorMessage = "Por favor ingrese los apellidos del empleado.")]
        public string apellidos { get; set; }

        [DisplayName("Dirección")]
        [Required(ErrorMessage = "Por favor ingrese la dirección del empleado.")]
        public string direccion { get; set; }

        [DisplayName("Teléfono")]
        [Required(ErrorMessage = "Por favor ingrese el teléfono del empleado.")]
        public string telefono { get; set; }

        [DisplayName("Sueldo base:")]
        [Required(ErrorMessage = "Por favor ingrese el sueldo base.")]
        [Range(0.00, 99999.99, ErrorMessage = "El precio ser entre 0.00 y 99999.00")]
        public Nullable<decimal> sueldo { get; set; }
        public int idDepartamento { get; set; }
        public byte eliminado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabulador> Tabulador { get; set; }

        public string GetFullName()
        {
            return this.nombre + ' ' + this.apellidos;
        }
    }
}
